from pandas import DataFrame


# ----------------------------------------------------------------------------------------------------------------------
# Arcitekten
def kw_architekten():
    return {'Dokumententyp': 'NO_VALUE!',
            'Dokumentensubtyp': 'NO_VALUE!',
            'Dateiname': 'NO_VALUE!',
            'result': 'NO_VALUE!',
            'Makler': 'NO_VALUE!',
            'Policen_ID': 'NO_VALUE!',
            'Version': 'NO_VALUE!',
            'Rahmenvertrag_ID': 'NO_VALUE!',
            'Ablaufdatum': 'NO_VALUE!',
            'VN Name': 'NO_VALUE!',
            'VN Str': 'NO_VALUE!',
            'VN PLZ': 'NO_VALUE!',
            'VN Ort': 'NO_VALUE!',
            'Versicherer': 'NO_VALUE!',
            'gültig ab': 'NO_VALUE!',
            'Änderungsgrund': 'NO_VALUE!',
            'AVB': 'NO_VALUE!',
            'AVB Stand': 'NO_VALUE!',
            'BB': 'NO_VALUE!',
            'BB_Stand': 'NO_VALUE!',
            'Ausschluss': 'NO_VALUE!',
            'Währung': 'NO_VALUE!',
            'SB': 'NO_VALUE!',
            'SB_min': 'NO_VALUE!',
            'SB_max': 'NO_VALUE!',
            'Zahlweise': 'NO_VALUE!',
            'Einmalprämie_Brutto': 'NO_VALUE!',
            'Brutto_gem_zahlweise': 'NO_VALUE!',
            'Netto_gem_Zahlweise': 'NO_VALUE!',
            'JNP': 'NO_VALUE!',
            'BJP': 'NO_VALUE!',
            'Min_Prämie': 'NO_VALUE!',
            'Deckung': 'NO_VALUE!',
            'Wagnis': 'NO_VALUE!',
            'Prämienfaktor': 'NO_VALUE!',
            'Höchstentschädigung': 'NO_VALUE!',
            'Anzahl_versicherte_Personen': 'NO_VALUE!',
            'Produkt': 'NO_VALUE!',
            'Betriebsart': 'NO_VALUE!',
            'DS_Vorsorge': 'NO_VALUE!',
            'Versicherungssumme': 'NO_VALUE!',
            'Mitversichert': 'NO_VALUE!',
            'beschäftigte': 'NO_VALUE!',
            'Mindestbeitrag': 'NO_VALUE!',
            'Risiko': 'NO_VALUE!',
            'DS_PS': 'NO_VALUE!',
            'DS_PS_max': 'NO_VALUE!',
            'DS_VS': 'NO_VALUE!',
            'DS_VS_max': 'NO_VALUE!',
            'DS_pauschal_PVS_privat': 'NO_VALUE!',
            'DS_pauschal_PVS_max_privat': 'NO_VALUE!',
            'DS_pauschal_PVS_privat_jePerson': 'NO_VALUE!',
            'DS_pauschal_PVS_privat_jePerson_max': 'NO_VALUE!',
            'DS_pauschal_PS_privat': 'NO_VALUE!',
            'DS_pauschal_PS_max': 'NO_VALUE!',
            'DS_pauschal_V_privat': 'NO_VALUE!',
            'DS_PS_Umwelt': 'NO_VALUE!',
            'DS_SS_Umwelt': 'NO_VALUE!',
            'DS_PS_max_Umwelt': 'NO_VALUE!',
            'DS_SS_max_Umwelt': 'NO_VALUE!',
            'DS_VS_Umwelt': 'NO_VALUE!',
            'DS_VS_Umwelt_max': 'NO_VALUE!',
            'Umsatz_ohne_USA': 'NO_VALUE!',
            'Umsatz_USA': 'NO_VALUE!',
            'PHV_Deckung': 'NO_VALUE!',
            'PHV_max': 'NO_VALUE!',
            'Umwelt_Deckung': 'NO_VALUE!',
            'Versicherungsort_Name': 'NO_VALUE!',
            'Versicherungsort_Str': 'NO_VALUE!',
            'Versicherungsort_PLZ': 'NO_VALUE!',
            'Versicherungsort_Ort': 'NO_VALUE!',
            'Verischerungsort_Land': 'NO_VALUE!',
            'Versicherungsort_Anzahl_Risiken': 'NO_VALUE!',
            'DS_Sach': 'NO_VALUE!',
            'DS_pauschal_PVS': 'NO_VALUE!',
            'Mietwert': 'NO_VALUE!',
            'DS_PS_SACH': 'NO_VALUE!',
            'DS_Umwelt_pauschal': 'NO_VALUE!',
            'SB_VS': 'NO_VALUE!',
            'SB_VS_USA': 'NO_VALUE!',
            'DS_Rückruf': 'NO_VALUE!',
            'DS_Rückruf_max': 'NO_VALUE!',
            'SB_Rückruf': 'NO_VALUE!',
            'SB_Rückruf_USA': 'NO_VALUE!',
            'DS_Ausbau_max': 'NO_VALUE!',
            'SB_Ausbau': 'NO_VALUE!',
            'SB_Ausbau_Min': 'NO_VALUE!',
            'SB_Ausbau_Max': 'NO_VALUE!',
            'SB_Ausbau_USA': 'NO_VALUE!',
            'SB_Ausbau_USA_Min': 'NO_VALUE!',
            'SB_Ausbau_USA_max': 'NO_VALUE!',
            'DS_Prüfkosten': 'NO_VALUE!',
            'DS_Prüfkosten_max': 'NO_VALUE!',
            'SB_Prüfkosten': 'NO_VALUE!',
            'SB_Prüfkosten_USA': 'NO_VALUE!',
            'mitversicherte Unternehmen': 'NO_VALUE!',
            'Strasse_mitversicherte': 'NO_VALUE!',
            'PLZ_mitversicherte': 'NO_VALUE!',
            'Ort_mitversicherte': 'NO_VALUE!',
            'SB_Naturschutz': 'NO_VALUE!',
            'VS_Asbest': 'NO_VALUE!',
            'VS_Asbest_max': 'NO_VALUE!',
            'VS_Asbest_SB': 'NO_VALUE!',
            'SB_Umwelthaftpflicht': 'NO_VALUE!',
            'SB_Diskriminierung': 'NO_VALUE!',
            'VS_Diskriminierung': 'NO_VALUE!',
            'THV_Deckung': 'NO_VALUE!',
            'Regulierung bis': 'NO_VALUE!'
            }


diff_list_architekten = ['Vertragsbeginn', 'Jahresnettobeitrag', 'Vertragsgrundlagen', 'Versicherungssummen',
                         'Mindestbeitrag', 'Naturschutzpolice', 'Versicherung-Nr', 'Haftpflichtversicherung', 'Gültig',
                         'Aufgehoben',
                         'Zahlungsweise', 'Diskriminierung', 'Selbstbeteiligung', 'Umwelthaftpflicht-Basisversicherung',
                         'einzelne',
                         'Asbestschäden', 'Naturschutzpolice', 'Ersatzanspruchen', 'Privatrisiken', 'Hundehalter',
                         'Berechnung',
                         'Vermogensschäden', 'Umweltschaden-Risiken', 'Umwelt-/Gewässerschadenhaftpflicht-Risiken',
                         'Aufhebungsgrund',
                         'Personenschäden', 'einzelne', 'Bedingungen', 'Ausgabe', 'ausgehändigt', 'Besondere',
                         'Regulierung']
# ----------------------------------------------------------------------------------------------------------------------
# ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# ----------------------------------------------------------------------------------------------------------------------
# Revision
synonyms = DataFrame.from_dict(
    {'total amount': ['Gesamtbetrag', 'Gesamt', 'Rechnungsendbetrag', 'TotalEURinkl.MWSt', 'Brutto-Endbetrag',
                      'Rechnungsbetrag', 'Rechnungssumme', 'Gesamtsumme', 'End-Preis', 'endbetrag',
                      'Bruttobetrag', 'EURinkl'],
     'tax': ['Mehrwertsteuer', 'Ust.19,00%', '19,00%MwSt', 'MwSt19,00%',
             'ges.MwSt', 'Mehrwertsteuer19,00%', 'Steuerbetrag', 'MWST%19,00', '16,00%MWSt',
             'Umsatzsteuer', 'MwSt.Betrag', 'USt.-pflichtiger Betrag', 'Ust.-Betrag', 'Ust.19%',
             '19%Ust', 'Ust.19,0%', 'MwStBetrag', '19%MwSt', 'mwst'],
     'total net': ['Netto', 'Nettowert', 'Netto-Auftragswert', 'Netto Warenwert', 'Nettobetrag',
                   'Gesamt-Nettobetrag', 'Zwischensumme', 'Netto ohne Durchläufer', 'GesamtNetto',
                   'USt.-pflichtiger Betrag', 'Summe', 'Nettosumme', 'Ust.-Basis', 'TotalEUR',
                   'GesamtbetragNetto', 'BETRAGOHNE'],
     'invoice number': ['belegnr', 'rechnungsnummer', 'rechnungnr', 'rechnr', 'rechnungsnr', 'rech-nr',
                        'rechnung-nr', 'rechnungs-nr', 'Beleg-nr'],
     'invoice date': ['datum', 'rechnungsdatum', 'vom', 'belegdatum', 'rechdat', 'rechdatum', 'weiden']
     }, orient='index')



# ------------- elektronik
def kw_elektronik():
        return {"Dokumententype": "Versicherungsscheins",
                "Dokumentensubtype": "Technische Versicherungen",
                "Dateiname": "NO_VALUE",
                "Versicherer": "NO_VALUE",
                "Policen_ID": "NO_VALUE",
                "VN Name": "NO_VALUE",
                "VN Str": "NO_VALUE",
                "VN PLZ": "NO_VALUE",
                "VN Ort": "NO_VALUE",
                "Produkt": "NO_VALUE",
                "gültig ab": "NO_VALUE",
                "Versicherungsort_Str": "NO_VALUE",
                "Versicherungsort_PLZ": "NO_VALUE",
                "Versicherungsort_Ort": "NO_VALUE",
                "Wagnis": "NO_VALUE",
                "Versicherungssumme": "NO_VALUE",
                "JNP": "NO_VALUE",
                "BJP": "NO_VALUE",
                "AVB": "NO_VALUE",
                "Makler": "NO_VALUE",

                "Position": "NO_VALUE",
                "Stand": "NO_VALUE",
                "Geräteart": "NO_VALUE",
                "Klauseln": "NO_VALUE",
                "Hersteller Modul": "NO_VALUE",
                "Hersteller Wechselrichter": "NO_VALUE",
                "Leistung": "NO_VALUE",
                "Baujahr": "NO_VALUE",
                "VSU": "NO_VALUE",
                "SB": "NO_VALUE",
                "Anzahl": "NO_VALUE",
                "PRT_brutto": "NO_VALUE",
                "BU": "NO_VALUE",
                "Haftzeit": "NO_VALUE",

                "Version": "NO_VALUE",
                "Rahmenvertrag_ID": "NO_VALUE",
                "Ablaufdatum": "NO_VALUE",
                "Änderungsgrund": "NO_VALUE",
                "AVB Stand": "NO_VALUE",
                "BB": "NO_VALUE",
                "BB_Stand": "NO_VALUE",
                "Ausschluss": "NO_VALUE",
                "Währung": "NO_VALUE",
                "SB": "NO_VALUE",
                "SB_min": "NO_VALUE",
                "SB_max": "NO_VALUE",
                "Zahlweise": "NO_VALUE",
                "Einmalprämie_Brutto": "NO_VALUE",
                "Brutto_gem_zahlweise": "NO_VALUE",
                "Netto_gem_Zahlweise": "NO_VALUE",

                "Min_Prämie": "NO_VALUE",
                "Deckung": "NO_VALUE",
                "Prämienfaktor": "NO_VALUE",
                "Höchstentschädigung": "NO_VALUE",
                "Anzahl_versicherte_Personen": "NO_VALUE",
                "Umsatz_ohne_USA": "NO_VALUE",
                "Umsatz_USA": "NO_VALUE",
                "Mietwert": "NO_VALUE",
                "Betriebsart": "NO_VALUE",
                "DS_Vorsorge": "NO_VALUE",
                "Mitversichert": "NO_VALUE",
                "beschäftigte": "NO_VALUE",
                "Tabelle Versicherungsorte": "NO_VALUE",
                # Versicherungsort_Name (1-99)
                # Verischerungsort_Land(1-99)
                "Tabelle GERÄTE": "NO_VALUE"

}